// mockData.ts
export const mockData = [
  {
    id: 0,
    label: "Club Mirage",
    color: "#FF4D4F",
    image: "https://picsum.photos/seed/clubmirage/256",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationmirage/400/250",
  },
  {
    id: 1,
    label: "Bar Lumos",
    color: "#1890FF",
    image: "https://picsum.photos/seed/barlumos/256",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationlumos/400/250",
  },
  {
    id: 2,
    label: "Electra",
    color: "#52C41A",
    image: "https://picsum.photos/seed/electra/256",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationelectra/400/250",
  },
  {
    id: 3,
    label: "Neon Nights",
    color: "#9C27B0",
    image: "https://picsum.photos/seed/neonnights/256",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationneon/400/250",
  },
  {
    id: 4,
    label: "The Velvet Room",
    color: "#E91E63",
    image: "https://picsum.photos/seed/velvetroom/256",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationvelvet/400/250",
  },
  {
    id: 5,
    label: "Skyline Bar",
    color: "#00BCD4",
    image: "https://picsum.photos/seed/skylinebar/256",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationskyline/400/250",
  },
  {
    id: 6,
    label: "Midnight Pulse",
    color: "#FF9800",
    image: "https://picsum.photos/seed/midnightpulse/256",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationmidnight/400/250",
  },
  {
    id: 7,
    label: "Aurora Lounge",
    color: "#4CAF50",
    image: "https://picsum.photos/seed/auroralounge/256",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationaurora/400/250",
  },
];
