export const mockData = [
  {
    id: 0,
    label: "Club Mirage",
    image: "images/locations/IMG-20250809-WA0018.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "/images/locations/IMG-20250809-WA0011.jpg",
  },
  {
    id: 1,
    label: "Bar Lumos",
    image: "images/locations/IMG-20250809-WA0012.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationlumos/400/250",
  },
  {
    id: 2,
    label: "Electra",
    image: "images/locations/IMG-20250809-WA0013.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationelectra/400/250",
  },
  {
    id: 3,
    label: "Neon Nights",
    image: "images/locations/IMG-20250809-WA0014.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationneon/400/250",
  },
  {
    id: 4,
    label: "The Velvet Room",
    image: "images/locations/IMG-20250809-WA0015.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationvelvet/400/250",
  },
  {
    id: 5,
    label: "Skyline Bar",
    image: "images/locations/IMG-20250809-WA0016.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationskyline/400/250",
  },
  {
    id: 6,
    label: "Midnight Pulse",
    image: "images/locations/IMG-20250809-WA0017.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationmidnight/400/250",
  },
  {
    id: 7,
    label: "Aurora Lounge",
    image: "images/locations/IMG-20250809-WA0018.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationaurora/400/250",
  },
  {
    id: 8,
    label: "Solar Flare",
    image: "images/locations/IMG-20250809-WA0019.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationsolarflare/400/250",
  },
  {
    id: 9,
    label: "Echo Chamber",
    image: "images/locations/IMG-20250809-WA0020.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationecho/400/250",
  },
  {
    id: 10,
    label: "Lunar Lounge",
    image: "images/locations/IMG-20250809-WA0021.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationlunar/400/250",
  },
  {
    id: 11,
    label: "Pulse Point",
    image: "images/locations/IMG-20250809-WA0022.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationpulse/400/250",
  },
  {
    id: 12,
    label: "Crimson Tide",
    image: "images/locations/IMG-20250809-WA0023.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationcrimson/400/250",
  },
  {
    id: 13,
    label: "Blue Velvet",
    image: "images/locations/IMG-20250809-WA0024.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationbluevelvet/400/250",
  },
  {
    id: 14,
    label: "Radiant Room",
    image: "images/locations/IMG-20250809-WA0025.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    locationImg: "https://picsum.photos/seed/locationradiant/400/250",
  },
  {
    id: 15,
    label: "Vortex",
    image: "images/locations/IMG-20250809-WA0026.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    locationImg: "https://picsum.photos/seed/locationvortex/400/250",
  },
];
